[build]
builder = "NIXPACKS"
buildCommand = "pnpm run build"

[build.nixpacksPlan.phases.install]
cmds = ["rm -rf node_modules && rm-rf .next && rm pnpm-lock.yaml && pnpm install && pnpm install --no-frozen-lockfile"]

[deploy]
startCommand = "pnpm run start"