[build]
builder = "NIXPACKS"
buildCommand = "pnpm run build --no-lint"

[build.nixpacksPlan.phases.install]
cmds = ["rm -rf .next && rm -rf node_modules && rm pnpm.lock.yaml && pnpm install --no-frozen-lockfile"]

[deploy]
startCommand = "pnpm run start"